In [ ]:
import torch

In [4]:
B = 2
d = 5
K = 10
H = torch.randn(B, d)
W = torch.randn(d, K)

In [5]:
print(H)

tensor([[ 0.0855, -0.9382, -1.0874, -0.1199,  0.1954],
        [-1.0851, -0.5325, -0.6179,  1.8915,  1.2001]])


In [6]:
print(W)

tensor([[ 1.4312, -0.2968,  0.4988,  0.4924,  0.3102, -0.9185, -0.3232,  0.9647,
         -0.0254, -0.9196],
        [ 0.9457,  1.2960,  1.1203, -1.8730, -0.9057,  1.4638, -0.3205,  0.4202,
         -0.7980, -0.1018],
        [-1.2374,  0.6957,  0.6055, -2.6668, -0.0166, -0.9164,  0.2272, -0.5305,
         -0.6770,  0.1091],
        [-1.0104,  0.6874,  1.5926, -2.8893, -0.7684,  0.3507,  0.2068,  0.5255,
         -0.1195, -0.5165],
        [ 0.0471, -0.8722, -0.2331,  0.1574, -0.2418,  0.1179,  0.9156,  1.2464,
         -1.7429, -1.5018]])


In [8]:
HW = H @ W
print(HW)

tensor([[ 0.7109, -2.2506, -1.9034,  5.0765,  0.9392, -0.4744,  0.1801,  0.4455,
          1.1565, -0.3332],
        [-3.1467, -0.5443,  1.2208, -3.1652, -1.5877,  1.5883,  1.8710,  1.5472,
         -1.4470, -1.7948]])


In [17]:
y = torch.tensor([1,9])
y = y.unsqueeze(1)
print(y)
l = HW.gather(1, y)
print(l)

tensor([[1],
        [9]])
tensor([[-2.2506],
        [-1.7948]])


In [22]:
new_HW = HW - l
print(new_HW)

tensor([[ 2.9615,  0.0000,  0.3472,  7.3271,  3.1898,  1.7762,  2.4307,  2.6961,
          3.4071,  1.9174],
        [-1.3520,  1.2504,  3.0155, -1.3705,  0.2071,  3.3831,  3.6657,  3.3420,
          0.3478,  0.0000]])


In [23]:
rows = torch.arange(B)
print(rows)
cols = torch.tensor([1,9])
new_HW[rows, cols] = -torch.inf
print(new_HW)

tensor([0, 1])
tensor([[ 2.9615,    -inf,  0.3472,  7.3271,  3.1898,  1.7762,  2.4307,  2.6961,
          3.4071,  1.9174],
        [-1.3520,  1.2504,  3.0155, -1.3705,  0.2071,  3.3831,  3.6657,  3.3420,
          0.3478,    -inf]])


In [24]:
loss = torch.max(new_HW)

In [25]:
print(loss)

tensor(7.3271)
